name: PR Summary to Slack

on:
  push: 
    branches:
      - main
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  generate-pr-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openai PyGithub
        
    - name: Generate PR Summary
      id: generate_summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Set time range and branches
        TIME_RANGE="1w"
        BRANCHES="main-v2,main-v3"
        
        echo "Generating PR summary for time range: $TIME_RANGE"
        echo "Analyzing branches: $BRANCHES"
        
        # Generate summary
        python github_pr_analyzer.py DrivetrainAi/drive \
          --time-range "$TIME_RANGE" \
          --branches $BRANCHES \
          --output-format json \
          --output-file pr_summary.json
        
        # Extract summary and stats
        python -c "
        import json
        import os
        
        with open('pr_summary.json', 'r') as f:
            data = json.load(f)
        
        summary = data.get('summary', 'No summary generated')
        stats = data.get('statistics', {})
        
        # Save summary to file
        with open('summary.md', 'w') as f:
            f.write(summary)
        
        # Set outputs for GitHub Actions
        print(f'::set-output name=summary::{summary[:1000]}...' if len(summary) > 1000 else f'::set-output name=summary::{summary}')
        print(f'::set-output name=pr_count::{stats.get(\"total_prs\", 0)}')
        print(f'::set-output name=time_range::{os.environ.get(\"TIME_RANGE\", \"1w\")}')
        "
        
    - name: Send to Slack
      uses: slackapi/slack-github-action@v1.24.0
      if: success()
      with:
        channel-id: C079CKC5LCS
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "🚀 GitHub PR Summary - DrivetrainAi/drive",
                  "emoji": true
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "📅 Time Period: ${{ steps.generate_summary.outputs.time_range }} | 📊 Total PRs: ${{ steps.generate_summary.outputs.pr_count }} | ⏰ Generated: ${{ github.event.created_at }}"
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "```${{ steps.generate_summary.outputs.summary }}```"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "🤖 Generated automatically by GitHub Actions | 📁 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
    - name: Send error notification
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "❌ PR Summary Generation Failed",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "The automated PR summary generation failed. Please check the GitHub Actions logs for details."
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "🔗 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Failed Run>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}